; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC-1 on Sat Aug 22 2020 17:37:15 GMT+0200 (Mitteleuropäische Sommerzeit)
M280 P0 S90 ; retract BLTouch

