; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC-1 on Sat Aug 22 2020 17:37:16 GMT+0200 (Mitteleuropäische Sommerzeit)

